name: CoderCo Container image to DockerHub workflow

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2


